name: rinha-backend-2023-q3
services:
    api1: &api
        image: wagfm/flask-api:0.1
        container_name: rinha-backend-api-1
        build:
            .
        environment: &api_env
            WEB_BIND: 127.0.0.1:5001
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432
            POSTGRES_USER: rinha-backend
            POSTGRES_PASSWORD: rinha123
            POSTGRES_DATABASE: persons_db
        volumes:
            - .:/app
        depends_on:
            postgres:
                condition: service_healthy
        restart: on-failure
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.38
                    memory: 0.75GB

    api2:
        <<: *api
        container_name: rinha-backend-api-2
        environment:
            <<: *api_env
            WEB_BIND: 127.0.0.1:5002

    postgres:
        container_name: rinha-backend-postgres
        image: postgres:12.19-alpine
        command: postgres -c 'max_connections=400' -c 'log_statement=none'
        environment:
            PGUSER: rinha-backend
            POSTGRES_USER: rinha-backend
            POSTGRES_PASSWORD: rinha123
            POSTGRES_DB: persons_db
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U rinha-backend -d persons_db" ]
            interval: 5s
            timeout: 5s
            retries: 20
            start_period: 10s
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.60
                    memory: 1.0GB

    nginx:
        container_name: rinha-backend-nginx
        image: nginx:1.27-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api1
            - api2
        network_mode: host
        deploy:
            resources:
                limits:
                    cpus: 0.14
                    memory: 0.5GB
